---
title: 'Read Me'
author: 'Florian Muthreich'
date: '2020/02/04'
output: pdf_document
---

#Lab-Notes
Samples 2020-02-13
Vial  Sample         Pinus  Betula  Salix  Spores
5*    A4-DL 138-140  +++    +              +++
4     D4-DL 161-163  ++     +              +++
4*    A5-UR  64- 66  ++     +       1      +++

1. add 1 cube to vial (~1cm^-3^)
2. wash with water -> dissolve sediment vortex
3. centrifuge 3min 3000rpm
4. decant; save decant
5. add 3 ml 1.43 SPT solution
6. vortex
7. centrifuge 3min 3000rpm
8. decant supernatant into new vial
9. repeat 5-7; decant into same vial
10. wash with water; save decant for checking
11. wash with water; save decant x2
12. wash residue with water; save in vial

2nd Run
Vial  Sample
2*    A4-DL 188-190
3*    A5-UR  72- 74
5     D4-DL 182-184
6     A4-DL 130-132
7*    A4-DL 163-165

3rd Run
Vial  Sample
4     A4-DL 175-177
5     D4-DL 149-151
6     A4-DL 145-147
7*    D4-DL 138-140

Samples 2020-02-19
Vial  Samples
1     TSK15-K6 42.0-42.8
2*    TSK15-K6 17.5-18.2
3*    TSK15-K6 38.7-39.2
4*    TSK15-K6  9.8-10.5
4     TSK15-K6 26.0-26.8
5     TSK15-K6  0.0- 1.5
5*    TSK15-K6 14.0-14.5
6     TSK15-K6 34.0-35.0
7     TSK15-K6 29.5-31.0
8     TSK15-K6 21.5-22.2

Meeting with Boris
higher microscope
tradeoff more time less image
BSi region showing up on the spectra
36x 1 px = 1 µm
testing of objective

#Plan for Ås Lab work

dependant on results from Boris tests

Status after last update that binding medium is working:
- much better picture than on ZnSe slides
- only measured empty sample
- normal objectiv works, no switching objectives needed
- if comparison to modern material, needs to be measured on new setup as well, cant use old data
Problems:
- Pollen density on slides
- unknownd layer over pollen; BSi? (maybe more washing, switching to store in alcohol instead of water?)

Possible set ups:
1. Measure one core. Multiple samples (5+), multiple species (3+) -> 15 samples
2. measure multiple cores (5+), reduced number of samples (<3) and red species (1; only Pinus) -> 15 samples

RQ for both setups:
Description of method for FTIR analysis of single grain fossil pollen

specific to 1: 
RQ1 Taxonomic differences between fossil pollen
RQ2 change in pollen chem with age (finer scale 100s of years)

specific to 2:
RQ1 chem differences of same species between cores (assuming P. sylvestris everwhere)
RQ2 change in pollen with age (broader scale 1000s of years)
